# Generated by Django 4.1.4 on 2022-12-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is comleted')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('image', models.ImageField(upload_to='todo_images/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'todo',
                'verbose_name_plural': 'Todos',
            },
        ),
    ]
